package com.sap.cap.esmapi.utilities.enums;

public enum EnumMessageType
{
    ERR_RATELIMIT, ERR_PAYLOAD, ERR_SRVCLOUDAPI, SUCC_ACC_CREATE, ERR_ACC_CREATE, SUCC_CASE_SUBM, ERR_CASE_CATG,
    ERR_ATTACHMENT,SUCC_CASE_CREATE,ERR_CASE_CREATE
}
