### Get Cases 
GET http://localhost:9090/api/cases
Accept: application/json 

### Get ESS Portal View
GET http://localhost:9090/api/ESS
Accept: application/json 

### Get Case Details in ESS Format
GET http://localhost:9090/api/casesESS
Accept: application/json 

### Get # of Cases 
GET http://localhost:9090/api/casesCount
Accept: application/json 


### Get Case Ids and GUIDS 
GET http://localhost:9090/api/caseIds
Accept: application/json 

### Get Cases GUIDS Only
GET http://localhost:9090/api/casesAnatomy
Accept: application/json 

### Get Account ID by Email
GET http://localhost:9090/api/accByEmail/?email=sunny.bhardwaj@sap.com
Accept: application/json 

### Get Contact ID by Email
GET http://localhost:9090/api/cpByEmail/?email=sunny.bhardwaj@sap.com
Accept: application/json 