### Get Cases 
GET http://localhost:9090/api/cases
Accept: application/json 

### Get # of Cases 
GET http://localhost:9090/api/casesCount
Accept: application/json 

### Get Cases GUIDS Only
GET http://localhost:9090/api/casesAnatomy
Accept: application/json 

### Get Account ID by Email
GET http://localhost:9090/api/accByEmail/?email=mikemiller@gmail.com
Accept: application/json 